# Generated by Django 4.0.1 on 2022-02-24 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_date_posted_alter_video_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='film',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 12, 25, 38, 589338, tzinfo=utc), editable=False),
        ),
    ]
