# Generated by Django 4.0.1 on 2022-03-23 12:11

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_video_date_posted_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 12, 11, 39, 32599, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'avi', 'webm'])]),
        ),
    ]
