# Generated by Django 4.0.1 on 2022-03-23 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_video_date_posted_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 17, 20, 53, 159610, tzinfo=utc), editable=False),
        ),
    ]
